# Generated by Django 3.1.7 on 2021-02-20 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='news.Category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('s', 'статья'), ('h', 'новость')], max_length=1, verbose_name='выбор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
    ]
